[package]
name = "gulagcleaner"
version = "0.1.0"
edition = "2021"
debuginfo-level = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gulagcleaner"
crate-type = ["lib"]

[dependencies]
flate2 = "1.0.27"
lopdf = "0.31.0"
